$ANSIBLE_VAULT;1.2;AES256;nlo
32313232643430653133613161663265616664386334663663333764383438353930303238353735
3737376161306530366464326666323132363334326538310a653066613433663063346130646363
64636636306230316332613961646461343963326365633063663465653565323437373531316430
3661316163633235660a313564316533336665656334373466373737336536393832333239383833
31343635373039643831656461373765623638636364326231363964623163643862663332323431
38623335356266663138313364356164326661393034613230626531656461396363333734656664
34663165333538663231363965333430373939343230356332666235633039613134663533353061
39323630396564383463393837346662343733303533613234313166633932383238653365363561
62666162613030313430653933313964336438303939366437346636316365333038646432346634
32346566326336356530663735393666643239656337373564306666646136393037653962303364
65353662653233643565616231316532343564323330363235376162363133303632636236333031
63633364303465636330333965636639303436623536323266323664303035663966373764313066
38623861636361343238373666616632663732623364353135343632663939363366333238393030
39326639356134386630393263633137353163633662623964633261626361343337613032656536
623231623232383437396262376230623566
