$ANSIBLE_VAULT;1.2;AES256;nlo
64626333636534316137393432356133626439623330303161646563363630616634653136333331
6666373334373333336461353636343339366535613135640a316134393734616237656666626234
64653661373634623534323733626630356631316166366131623232653633646431316130666531
3237646166343034610a353230323331303936313166613135653835616433336334643430623036
32663035393434653930633563313535383733396139343963353130636662643039373936373362
33616234666364376636616134633132613561616466376137333739376330656464663862323834
326262666331383866646239313938656138
